### ISSUE TITLE
[ANIRip] Error : There was an error while starting the rtmpdump command... : exit status 1

### ISSUE THREAD

**Issue by lbickmore** [sdwolfe32/anirip#1]
[ANIRip] Error : There was an error while starting the rtmpdump command... : exit status 1

Error occurs upon my attempt to download any anime. I chose to test some of the urls listed in the readme as well.

I ran `anirip http://www.crunchyroll.com/attack-on-titan`
and got   

```
ANIRip v1.4.0(7/7/2016) - by Steven Wolfe <steven@swolfe.me>
[ANIRip] Getting a list of episodes for the show...
[ANIRip] Getting Episode Info...
[ANIRip] Downloading Attack on Titan - S01E00 - PV
[ANIRip] Downloading video...
[ANIRip] Error : There was an error while starting the rtmpdump command... : exit status 1
[ANIRip] Getting Episode Info...
[ANIRip] Downloading Attack on Titan - S01E01 - To You, 2,000 Years in the Future -The Fall of Zhiganshina (1)
[ANIRip] Downloading video...
[ANIRip] Error : There was an error while starting the rtmpdump command... : exit status 1
[ANIRip] Getting Episode Info...
[ANIRip] Downloading Attack on Titan - S01E02 - That Day - The Fall of Zhiganshina (2)
[ANIRip] Downloading video...
[ANIRip] Error : There was an error while starting the rtmpdump command... : exit status 1
[ANIRip] Getting Episode Info...
```

I've got all current versions of the programs listed in the readme and I've tried having them part of the PATH as well as in the same directory. Thoughts?

**Comment by sdwolfe32** [comment]
Hey Ibickmore, I did a little debugging to try and figure out the issue and it appears as though Crunchyroll is no longer using an RTMP stream provider to serve their video, as the XML body received for each episode no longer contains the 2 URLs needed for rtmpdump. It seems like they're now using an M3U8 stream which can dumped to a transport-stream file relatively easy using ffmpeg. 

As I'm going to be very busy this weekend I don't think I'll have time to implement a fix in the next few days however once I'm back home I'll reimplement the fix as soon as possible.

**Comment by lbickmore** [comment]
Thanks for the update! Don't rush anything on my account! I'll keep an eye out for any new commits though!

**Comment by sdwolfe32** [comment]
So while I was in the process of addressing this bug today, I noticed the xml received from crunchyroll is no longer using M3U8 streams and has reverted back to RTMP. I'm assuming either they were testing another streaming protocol temporarily or are currently split testing and I just so happened to get hit with RTMP urls. The ripper seems to be working as of right now for me however.

Please let me know if it's the same for you.

**Comment by lbickmore** [comment]
Interesting! It appears to be working for New-Game atm. I'll try a few different anime's and respond here with results. Thanks for the followup.
