### ISSUE TITLE
Unable to handle special characters on Windows

### ISSUE THREAD

**Issue by HalfDemon** [sdwolfe32/anirip#10]
Due to the way windows works anirip/GO has issues dealing with reserved characters, as shown in log1.txt. I propose the affected characters should be stripped in order to enable the expected functionality on shows where Crunchyroll uses a reserved character in the name. The following characters (below) are from the page https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx under heading File and Directory Names, subheading Naming Conventions. 

In practice the only character I've seen used is the ?(question mark), but I can't say they haven't used any of the other ones.

Reserved Characters
    < (less than)
    > (greater than)
    : (colon)
    " (double quote)
    / (forward slash)
    \ (backslash)
    | (vertical bar or pipe)
    ? (question mark)
    * (asterisk)

[log1.txt](https://github.com/sdwolfe32/anirip/files/1735404/log1.txt)

**Comment by theclickman** [comment]
That piece of code exists but was not applied to the name of the show, only to the episode name. I did push a code fix suggestion for that to the author.

**Comment by sdwolfe32** [comment]
I've merged your PR clickman. Sorry this isn't my most active project so I have a tough time keeping up with issues. Hopefully his change fixes your issue!
