### ISSUE TITLE
There was an error parsing show metadata

### ISSUE THREAD

**Issue by Dokman** [sdwolfe32/anirip#2]
Why i am having this problem?

![image](https://cloud.githubusercontent.com/assets/2290904/18384586/a96574d8-768b-11e6-86cd-3578e1c61f88.png)

**Comment by sdwolfe32** [comment]
So while I was in the process of addressing this bug today, I noticed the xml received from crunchyroll is no longer using M3U8 streams and has reverted back to RTMP. I'm assuming either they were testing another streaming protocol temporarily (at the time you used it) or are currently split testing and I just so happened to get hit with RTMP urls. The ripper seems to be working as of right now for me however.

Please let me know if it's the same for you.

**Comment by sdwolfe32** [comment]
Also for spanish subtitles try "-l esp" or "-l Español"

**Comment by JibsouX** [comment]
Same issue here : 

<img width="704" alt="capture 2016-09-21 a 02 04 19" src="https://cloud.githubusercontent.com/assets/5707449/18693208/3d02a568-7fa0-11e6-9075-5b0bcfcb7697.png">

**Comment by JibsouX** [comment]
Hy !
Is the project still in work ?
Tx :)
