### ISSUE TITLE
Runtime error index out of range (GO) (Daisuki)

### ISSUE THREAD

**Issue by JibsouX** [sdwolfe32/anirip#3]
I don't know why there is in the path c:/users/steeve ....
i use your last version of anirip; php 5.6.21, last Go package
Windows 7 64bit

<img width="642" alt="capture 2016-09-21 a 16 01 17" src="https://cloud.githubusercontent.com/assets/5707449/18714071/e6c267c2-8014-11e6-98a3-8bf13615d18b.png">

**Comment by sdwolfe32** [comment]
Support for daisuki has been removed for now. Crunchyroll should be working now. I'll explore supporting daisuki again in the future. Also sorry for the delayed response!
