### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Stonedestroyer** [sdwolfe32/anirip#4]
Compiling I get this on Windows Server 2016 using latest GO available. 
`
C:\Go\workspace>go get
# github.com/sdwolfe32/anirip/anirip
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:54: show.GetTitle undefined (type *Show is pointer to interface, not interface)
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:55: show.GetSeasons undefined (type *Show is pointer to interface, not interface)
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:58: show.GetTitle undefined (type *Show is pointer to interface, not interface)
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:62: undefined: err
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:62: undefined: quality
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:62: undefined: session in session.GetCookies
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:62: undefined: err
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:63: undefined: err in err.Error
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:68: undefined: err
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:68: show.GetTitle undefined (type *Show is pointer to interface, not interface)
src\github.com\sdwolfe32\anirip\anirip\interfaces.go:68: too many errors
`

**Comment by sdwolfe32** [comment]
Sorry for these issues and sorry for the late response. I just did a large update that should fix this.
